/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CtrInputMWH;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.MySQLConn;
import model.Parameter;

/**
 *
 * @author AG
 */
public class MDMWH extends javax.swing.JInternalFrame {

    Connection koneksi = null;
    PreparedStatement ps = null;
    Statement state = null;
    ResultSet rs = null;

    Parameter param;

    public Parameter getParam() {
        return param;
    }

    public void setParam(Parameter param) {
        this.param = param;
    }

    /**
     * Creates new form MWH
     */
    public MDMWH() {
        initComponents();
        setTitle("Pertamina Lubricants | MWH");
        param = new Parameter();
        CtrInputMWH cm = new CtrInputMWH();
        jxdTglMWH.setFormats(Parameter.formatDate);
        jxdTglMWH.setDate(new java.util.Date());
        tblMWH.setModel(cm.getModelInputMWH());
        setEditState(true);
        isiComboBox();
    }

    private void isiComboBox() {
        cmbPemasok.removeAllItems();
        try {
            koneksi = MySQLConn.getKoneksi();
            state = koneksi.createStatement();
            String query = "SELECT * FROM pemasok";

            rs = state.executeQuery(query);
            while (rs.next()) {

                String sNamaPemasok = rs.getString("nama_pemasok");
                cmbPemasok.addItem(sNamaPemasok);
            }
            rs.close();
            state.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    private void simpanMWH(String NoMWH, String NoForm, int idPemasok, String NoSuratJalan, String Warna, String JumlahPengiriman, String JumlahdiTest, String JenisBarang, String Ukuran, Date tanggal) {
        CtrInputMWH cm = new CtrInputMWH();
        cm.setNo_MWH(NoMWH);
        cm.setNo_form(NoForm);
        cm.getParam().setIdPemasok(idPemasok);
        //cm.setId_pemasok(idPemasok);
        cm.setNo_surat_jalan(NoSuratJalan);
        cm.setWarna(Warna);
        cm.setJmlh_pengiriman(JumlahPengiriman);
        cm.setTgl_MWH(tanggal);
        cm.setJmlh_di_test(JumlahdiTest);
        cm.setJenis_barang(JenisBarang);
        cm.setUkuran(Ukuran);
        cm.SimpanMWH();
    }

    private void ubahMWH(String NoMWH, String NoForm, int idPemasok, String NoSuratJalan, String Warna, String JumlahPengiriman, String JumlahdiTest, String JenisBarang, String Ukuran, Date tanggal) {
        CtrInputMWH cm = new CtrInputMWH();
        cm.setNo_MWH(NoMWH);
        cm.setNo_form(NoForm);
        cm.getParam().setIdPemasok(idPemasok);
        //cm.setId_pemasok(idPemasok);
        cm.setNo_surat_jalan(NoSuratJalan);
        cm.setWarna(Warna);
        cm.setJmlh_pengiriman(JumlahPengiriman);
        cm.setTgl_MWH(tanggal);
        cm.setJmlh_di_test(JumlahdiTest);
        cm.setJenis_barang(JenisBarang);
        cm.setUkuran(Ukuran);
        cm.ubahMWH();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtWarna = new javax.swing.JTextField();
        txtJmlPengiriman = new javax.swing.JTextField();
        txtJmlTest = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtJenisBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUkuran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnUbah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jxdTglMWH = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        cmbPemasok = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtNoMWH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNoForm = new javax.swing.JTextField();
        txtNoSuratJalan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMWH = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Jenis Barang :");

        jLabel10.setText(" Ukuran :");

        jLabel6.setText("Warna :");

        jLabel7.setText("Jumlah Pengiriman :");

        jLabel8.setText("Jumlah di Test :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJmlPengiriman)
                    .addComponent(txtJmlTest)
                    .addComponent(txtJenisBarang)
                    .addComponent(txtWarna, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(txtUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtJenisBarang, txtJmlPengiriman, txtJmlTest, txtWarna});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtJmlPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtJmlTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Control"));

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-validated-icon 32.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel-icon 24.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-icon 24.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnBatal))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatal, btnSimpan, btnUbah});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("No Surat Jalan :");

        jLabel2.setText("No Form :");

        jLabel3.setText("Pemasok :");

        jLabel1.setText("No MWH :");

        jLabel5.setText("Tgl MWH :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoSuratJalan, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jxdTglMWH, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoMWH, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNoForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNoMWH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNoForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNoSuratJalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jxdTglMWH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblMWH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMWH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMWHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMWH);

        jPanel8.setBackground(new java.awt.Color(255, 255, 102));

        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("Form ini digunakan untuk pengolahan data MWH");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("Form Entry Data MWH");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMWHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMWHMouseClicked
        CtrInputMWH cm = new CtrInputMWH();
        if (evt.getClickCount() == 1) {
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();
            setEditState(false);
            txtNoMWH.setText(target.getModel().getValueAt(row, 0).toString());
            txtNoForm.setText(target.getModel().getValueAt(row, 1).toString());
            String sIdPemasok = target.getModel().getValueAt(row, 2).toString();
            //int inIdPemasok = Integer.valueOf(sIdPemasok);
            //String namaPemasok = cm.getNamaPemasok(inIdPemasok);
            cmbPemasok.setSelectedItem(sIdPemasok);
            txtNoSuratJalan.setText(target.getModel().getValueAt(row, 3).toString());
            try {
                java.util.Date sDate = new SimpleDateFormat("yyy-MM-dd").parse(target.getModel().getValueAt(row, 4).toString());
                jxdTglMWH.setDate(sDate);
            } catch (ParseException ex) {
                Logger.getLogger(MDMWH.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtWarna.setText(target.getModel().getValueAt(row, 5).toString());
            txtJmlPengiriman.setText(target.getModel().getValueAt(row, 6).toString());
            txtJmlTest.setText(target.getModel().getValueAt(row, 7).toString());
            txtJenisBarang.setText(target.getModel().getValueAt(row, 8).toString());
            txtUkuran.setText(target.getModel().getValueAt(row, 9).toString());
        }
    }//GEN-LAST:event_tblMWHMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        CtrInputMWH cm = new CtrInputMWH();
        String sNoMWH = txtNoMWH.getText();
        String sNoForm = txtNoForm.getText();
        String namaPemasok = cmbPemasok.getSelectedItem().toString();
        String sNoSuratJalan = txtNoSuratJalan.getText();
        String sWarna = txtWarna.getText();
        String sJumlahPengiriman = txtJmlPengiriman.getText();
        String sJumlahdiTest = txtJmlTest.getText();
        String sJenisBarang = txtJenisBarang.getText();
        String sUkuran = txtUkuran.getText();
        Date sTanggal = new java.sql.Date(jxdTglMWH.getDate().getTime());
        if (sNoMWH.trim().equals("") || sNoForm.trim().equals("") || sNoSuratJalan.trim().equals("")
                || sWarna.trim().equals("") || sJumlahPengiriman.trim().equals("") || sJumlahdiTest.trim().equals("")
                || sJenisBarang.trim().equals("") || sUkuran.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please review you entry!");
        } else {
            int idPemasok = cm.getIdPemasok(namaPemasok);
            simpanMWH(sNoMWH, sNoForm, idPemasok, sNoSuratJalan, sWarna, sJumlahPengiriman, sJumlahdiTest, sJenisBarang, sUkuran, sTanggal);
            tblMWH.setModel(cm.getModelInputMWH());
            setEditState(false);
            cleartextfield();
            JOptionPane.showMessageDialog(this, "Add data successfull");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        CtrInputMWH cm = new CtrInputMWH();
        String sNoMWH = txtNoMWH.getText();
        String sNoForm = txtNoForm.getText();
        String namaPemasok = cmbPemasok.getSelectedItem().toString();
        String sNoSuratJalan = txtNoSuratJalan.getText();
        String sWarna = txtWarna.getText();
        String sJumlahPengiriman = txtJmlPengiriman.getText();
        String sJumlahdiTest = txtJmlTest.getText();
        String sJenisBarang = txtJenisBarang.getText();
        String sUkuran = txtUkuran.getText();
        Date sTanggal = new java.sql.Date(jxdTglMWH.getDate().getTime());
        if (sNoMWH.trim().equals("") || sNoForm.trim().equals("") || sNoSuratJalan.trim().equals("")
                || sWarna.trim().equals("") || sJumlahPengiriman.trim().equals("") || sJumlahdiTest.trim().equals("")
                || sJenisBarang.trim().equals("") || sUkuran.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please review your entry!");
        } else {
            int idPemasok = cm.getIdPemasok(namaPemasok);
            ubahMWH(sNoMWH, sNoForm, idPemasok, sNoSuratJalan, sWarna, sJumlahPengiriman, sJumlahdiTest, sJenisBarang, sUkuran, sTanggal);

            tblMWH.setModel(cm.getModelInputMWH());
            setEditState(false);
            cleartextfield();
            JOptionPane.showMessageDialog(this, "Update data successfull");
        }

    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        setEditState(true);
        cleartextfield();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void setEditState(boolean state) {
        btnSimpan.setEnabled(state);
        btnUbah.setEnabled(!state);
//      btnBatal.setEnabled(state);
    }

    private void cleartextfield() {
        txtJenisBarang.setText("");
        txtJmlPengiriman.setText("");
        txtJmlTest.setText("");
        txtNoForm.setText("");
        txtNoMWH.setText("");
        txtNoSuratJalan.setText("");
        txtUkuran.setText("");
        txtWarna.setText("");
        cmbPemasok.setSelectedIndex(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox cmbPemasok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jxdTglMWH;
    private javax.swing.JTable tblMWH;
    private javax.swing.JTextField txtJenisBarang;
    private javax.swing.JTextField txtJmlPengiriman;
    private javax.swing.JTextField txtJmlTest;
    private javax.swing.JTextField txtNoForm;
    private javax.swing.JTextField txtNoMWH;
    private javax.swing.JTextField txtNoSuratJalan;
    private javax.swing.JTextField txtUkuran;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables

}
